language: ruby
cache: bundler
rvm:
- 2.1.2
env:
  global:
  - AMAZON_S3_BUCKET=coffee-memo-bundle-cache
  - AMAZON_ACCESS_KEY_ID=AKIAIU4RV42E4B3FBUSQ
  - secure: "k3b72k4xCb2f9694PapuADSkbFapjOVwSaIJRbEL2HkHnZ+XhVbgy9cpnEbjnY1tCDBoYKM3DsHHNa8o6VTXjGwIC73kbcFMyBajJ0OvLOc4rBHx0TGmD0DA62JV0vCl7gMCaRWfdKo4Um55Imq9NlxZaC11MrLUYQ6gjbgPS2A="
  - RAILS_ENV=test
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- travis_retry script/cached-bundle install --deployment --without development
before_script:
- psql -c 'create database coffee_memo_test;' -U postgres
- cp config/database_travis.yml config/database.yml
- bundle exec rake db:migrate RAILS_ENV=test
script:
- bundle exec rake
- bundle exec rubocop -R --fail-level error